import { Poppins, Kanit } from 'next/font/google';
import './globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-poppins',
});

const kanit = Kanit({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-kanit',
});
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} font-sans`}>
      <body className="bg-gradient-to-r from-fuchsia-600 to-purple-600">
        {children}
      </body>
    </html>
  );
}
